//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeworX.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment : IEntityUID
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Appointment()
        {
            this.TopicToAppointment = new HashSet<TopicToAppointment>();
        }
    
        public System.Guid UID { get; set; }
        public string Description { get; set; }
        public string Detail { get; set; }
        public System.DateTime Date { get; set; }
        public System.Guid SubjectUID { get; set; }
    
        public virtual Subject Subject { get; set; }
        public virtual Exam Exam { get; set; }
        public virtual Homework Homework { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TopicToAppointment> TopicToAppointment { get; set; }
    }
}
