//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeworX.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exam : IEntityUID
    {
        public System.Guid UID { get; set; }
        public bool Remind { get; set; }
        public Nullable<System.DateTime> Time { get; set; }
        public string Mailadress { get; set; }
    
        public virtual Appointment Appointment { get; set; }
    }
}
