//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeworX.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HomeworXEntities : DbContext
    {
        public HomeworXEntities()
            : base("name=HomeworXEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Appointment> Appointment { get; set; }
        public virtual DbSet<Exam> Exam { get; set; }
        public virtual DbSet<Homework> Homework { get; set; }
        public virtual DbSet<Subject> Subject { get; set; }
        public virtual DbSet<Topic> Topic { get; set; }
        public virtual DbSet<TopicToAppointment> TopicToAppointment { get; set; }
    }
}
