//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeworX.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TopicToAppointment : IEntityUID
    {
        public System.Guid UID { get; set; }
        public System.Guid TopicUID { get; set; }
        public System.Guid AppointmentUID { get; set; }
    
        public virtual Appointment Appointment { get; set; }
        public virtual Topic Topic { get; set; }
    }
}
